### ISSUE TITLE
Support specifying runtime query parameters in cli

### ISSUE THREAD

**Issue by glguy** [ge-high-assurance/RACK#292]
The `data export` API needs to support specifying runtime parameters and multiple source graphs

The current API has two positional arguments: `rack data export <nodegroup> <graph>`

We'll need something like: `rack data export --graph http://x/y --graph http://y/z NodeGroup X=1 Y=2`

It'd be more verbose but perhaps easier to understand if we used named parameters for everything

```
rack data export \
  --graph http://x/y --graph http://y/z \
  --nodegroup=NodeGroup \
  --constraint=X=1 \
  --constraint=Y=2
```

**Comment by clarissa-adelard** [comment]
Does this mean a node group can apply to more than one source graph or be reused across different source graphs?

I thought node groups were linked to data sources - do they exist in a separate name space?

**Comment by glguy** [comment]
Nodegroups are independent from data sources. One nodegroup can query data from one or more data graphs. All the data indexed by SemTK is associated with a graph. This makes it possible to selectively enable, disable, delete, query different subsets of the data. (Support for multiple, concurrent data graphs in the CLI is already completed.)

**Comment by glguy** [comment]
You can find examples of how this feature works in the [README](https://github.com/ge-high-assurance/RACK/blob/master/cli/README.md#export-data)

**Comment by cuddihyge** [comment]
Nodegroup json files contain a specification to default graph(s),  but nodegroup operations typically specify a **connection**.   Each connection is two lists of graphs:  a list of graphs containing the ontology, and a list of graphs containing data.  In the simplest case all ontology and data can be in one graph.   

So you can change the ontology graph(s) if you model has moved (changing the model is likely to invalidate the nodegroup).   And by design you can change the data graph(s) to run the query against different data sets.

Adding "-graph" to CLI operations is not expressive enough.  We need to specify whether it is ontology or data.   Also need to make it clear that you're still using the nodegroup's default SPARQL endpoint url, and server type.  @glguy

**Comment by glguy** [comment]
We currently *only* support changing the data graph. Currently the RACK CLI assumes you're always using the RACK model. If we need to be able to change the model then I think we'll want a different flag. Is changing the model graph something we need to support?

**Comment by cuddihyge** [comment]
OK.  that makes sense.  I'm not sure when we'll get to the point that folks want to change their model (custom extensions/overlays), so changing only the data graph does make good sense for now.  If we haven't released the functionality yet, we may want to consider a flag other than plain "graph" so that when we do want to change the model the flags don't seem too awkward.

**Comment by glguy** [comment]
> OK. that makes sense. I'm not sure when we'll get to the point that folks want to change their model (custom extensions/overlays), so changing only the data graph does make good sense for now. If we haven't released the functionality yet, we may want to consider a flag other than plain "graph" so that when we do want to change the model the flags don't seem too awkward.

The flag as implemented/documented is currently `--data-graph`
