### ISSUE TITLE
SPARQLgraph functions to fix Nodegroups

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#326]
Change class of a node.
Change a property URI
Change a node.

Have SPARQLgraph attempt to re-validate after these changes.

**Comment by kityansiu** [comment]
I tested this using nodegroups from v4.1. The messages guided me through to fix the nodegroup. Then when it was fixed it told me that I now had a valid nodegroup. Excellent!

**Comment by kityansiu** [comment]
@cuddihyge: Reopening because something has emerged from testing. SemTK correctly guided me to fix a nodegroup (which had a property whose domain was changed). But after fixing the nodegroup, I was not able to ingest any data with it or even run the nodegroup. The attached ppt has screen captures. The nodegroup I was fixing was ingest-specification.json from the GrammaTech dataset named Boeing-CSV-20210504.

[fixingNodegroups.pptx](https://github.com/ge-high-assurance/RACK/files/6534470/fixingNodegroups.pptx)

**Comment by kityansiu** [comment]
Reviewed. Functionality for fixing nodegroups is working. I didn't test the exact issue I found originally with the ingest_specification.json nodegroup from GrammaTech because we have since reverted the move of definedIn property (#409).
