### ISSUE TITLE
ASSIST - write_ontology does not handle duplicate property names

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#481]
[See also #472]

The Prolog ontology files generated by `write_ontology` can clash with each other if two entities share the same property names.

For example, HAZARD and REQUIREMENT both have `author` and `mitigates` properties, so `write_ontology` generates `author` and `mitigates` predicates in `ontology/hazard` and `ontology/requirements`.

As a result, if you try to import both ontology files, you get a series of error messages due to the name clash:
```
?- [assist/bin/ontology/hazard].
true.
?- [assist/bin/ontology/requirements].
ERROR: import/1: No permission to import requirements:assert_mitigates/2 into user (already imported from hazard)
ERROR: import/1: No permission to import requirements:mitigates/2 into user (already imported from hazard)
ERROR: import/1: No permission to import requirements:author/2 into user (already imported from hazard)
ERROR: import/1: No permission to import requirements:assert_author/2 into user (already imported from hazard)
true.
```
I note that the SADL files that define HAZARD and REQUIREMENT avoid this problem by qualifying the property names, but  `write_ontology` strips off these prefixes:
```
uri "http://arcos.rack/HAZARD" alias H.

HAZARD
	is a type of ENTITY.

	H:mitigates (note "a HAZARD may be mitigated by a OP_PROCEDURE") describes OP_PROCEDURE with values of type HAZARD.

HAZARD_IDENTIFICATION
	is a type of ACTIVITY.

	H:author (note "AGENT(s) who work on this ACTIVITY") describes HAZARD_IDENTIFICATION with values of type AGENT.
	H:author is a type of wasAssociatedWith.
```
https://github.com/ge-high-assurance/RACK/blob/master/RACK-Ontology/ontology/HAZARD.sadl
```
uri "http://arcos.rack/REQUIREMENTS" alias Rq.

REQUIREMENT
	is a type of ENTITY.

	Rq:mitigates (note "ENTITY(s) (e.g. HAZARD) that is being mitigated by this REQUIREMENT") describes REQUIREMENT with values of type ENTITY.
	Rq:mitigates is a type of wasImpactedBy.

REQUIREMENT_DEVELOPMENT
	is a type of ACTIVITY.

	Rq:author (note "AGENT(s) responsible for producing a REQUIREMENT") describes REQUIREMENT_DEVELOPMENT with values of type AGENT.
	Rq:author is a type of wasAssociatedWith.
```
https://github.com/ge-high-assurance/RACK/blob/master/RACK-Ontology/ontology/REQUIREMENTS.sadl

Is it possible to fix this problem by importing the ontology files so that the predicates have qualified names, for example, `hazard:author` and `requirement:author`? Ideally, the qualification should only be necessary if the unqualified name is ambiguous.

**Comment by Ptival** [comment]
This is a limitation of the weak design of modules/imports in Prolog, but I believe there exists a workaround.

First, instead of using the load `[path/to/file].` command, you can instead use `use_module`, which will let you decide what comes in scope. However, if you simply `use_module(ontology(hazard)).`, it will still bring into scope all the symbols, and will emit the same error when loading module `requirements` subsequently.

The solution is to specify the import list to be empty. This will load the module so that exported symbols are available qualified. E.g.: 

```prolog
?- [assist/bin/paths].
true.
?- use_module(ontology(hazard), []).
true.
?- use_module(ontology(requirements), []).
true.
```

With this setup, you should be able to access `hazard:mitigates` and `requirements:mitigates` independently.

Unfortunately, I cannot think of a pleasant solution so that all three of these conditions are met:

- Non-conflicting symbols are available unqualified.
- Conflicting symbols are available qualified.
- No warning/error is displayed when loading modules with conflicting symbols.

For this, you'd have to manually exclude known conflicting symbols:

```prolog
?- [assist/bin/paths].
true.
?- use_module(ontology(hazard), except([mitigates/2, ...])).
true.
?- use_module(ontology(requirements), except([mitigates/2, ...])).
true.
; Here, you should be able to access the non-conflicting symbols unqualified, and the conflicting symbols qualified.
```

So I don't think we'll make any changes to the generation at the moment, except document this workaround. If this ever becomes a recurrent problem, we could have a less conflict-prone symbol generation, e.g. something like `hazard__mitigates` instead of `mitigates`.

**Comment by Robert-Adelard** [comment]
Thanks for the detailed analysis of the problem and the suggested workaround.

The underlying problem is caused by the duplicate property names in the core ontology.
