### ISSUE TITLE
ASSIST - RACKLIB - load_model_from_url reports 0 triples read

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#482]
If you use `load_model_from_url` or `load_model_from_rack` to load the model from a server, you are told that 0 triples have been read. This is clearly not the case because `save_model_to_file` reports that it saved several thousand triples...

```
$ swipl
Welcome to SWI-Prolog (threaded, 64 bits, version 8.2.4)

?- [assist/bin/rack/model].
true.

?- load_model_from_rack().
% Parsed "http://localhost:3030/RACK" in 0.22 sec; 0 triples
true.

?- save_model_to_file('localhost.model').
% Saved 3,490 triples about 638 subjects into stream(<stream>(0x1247042b0))
true.

?- ^D
% halt
```

**Comment by kquick** [comment]
This appears to be an issue in either the `semweb/rdf11` or the `semweb/turtle` libraries provided with SWI-Prolog.  It's also a message emitted by those libraries and not something we can control (although we can suppress the messages entirely by adding `silent(true)` to the options for `rdf_load`).  It's also interesting to note that specifying `format(turtle)` instead of `format(trig)` in the options results in a correct count, but also a warning about a a "Syntax error" and a note "assuming TriG, ignoring graphs".

This misleading report is unfortunate, but not something we can fix.

**Comment by kquick** [comment]
Added an informational message about the unfortunate reporting in https://github.com/ge-high-assurance/RACK/pull/498
