### ISSUE TITLE
Support SPARQL "union" in SemTK

### ISSUE THREAD

**Issue by AbhaMoitra** [ge-high-assurance/RACK#59]
An example of a query that we would be able to perform is as follows.
//RequirementVerificationGaps: Find requirements with either 
//                no Test 
//                or where some Test have not been run
//                or where some Test when run has failed

**Comment by cuddihyge** [comment]
Note that Abha's first query (thanks for this) exposed an inability of the new Semtk union to generate SPARQL with UNION and MINUS on the same object property.
I will fix this, but it will take a couple days of work time.

**Comment by cuddihyge** [comment]
I've built a sample of Abha's query (above)
1) I can review with Abha via screenshare only since opensource sparqlgraph and RACK docker don't yet have all the latest improved functions to run it
2) The major (hopefully not disruptive) changes to sparqlGraph UI required for UNIONS still contains a number of bugs that need to be fixed

Although this particular example is a fine test case, I'm curous about refactoring it as a non-UNION query of the form:

_requirement MINUS (test with result with success)_

**Comment by AbhaMoitra** [comment]
@cuddihyge: Yes it can be refactored to void "union" but this was simply a query written using "union" to test the functionality. Let me know if you want to show it to me.
