### ISSUE TITLE
SPARQLgraph adds newlines when downloading CSV

### ISSUE THREAD

**Issue by baoluomeng** [ge-high-assurance/RACK#650]
I stored a long String in SemTK. But when I query SemTK, the returned result is different on the website and the csv file. The csv file has the extra newline "\n" character inserted everywhere. See the snapshots below.

The result on the website.
![b3dc487e-14d0-453d-bdcf-8564f8f46b2d](https://user-images.githubusercontent.com/49253843/152051332-d5e86640-921f-44e4-b15e-d7dd4e2da89c.jpg)

The result in the csv file:
![c95deccb-437a-4f68-a969-e9029067e1df](https://user-images.githubusercontent.com/49253843/152051380-80225543-cd70-458d-a727-b37e2fd5e72c.jpg)

**Comment by cuddihyge** [comment]
I found that SemTK is using a home-grown over-simple algorithm to change Fuseki's json tables into CSV.
I will replace it with MIT licensed and respected CSV parser PapaParse.

**Comment by cuddihyge** [comment]
CSVs are parsed and unparsed in several places including: 
* parse CSV during ingestion
* store very large tables in a single JSON format and return in pieces in multiple formats
* display as HTML in SPARQLgraph,
* convert displayed HTML to csv, and 
* download the full csv directly through the service layer.

I have thoroughly reviewed and re-coded these processes using Apache CSVParser (java) and PapaParse (js).  

Junit test is DataLoaderTest_IT.testMessyStringsInCsv()

A test example is documented in the [Ingestion Type Handling SemTK wiki Page](https://github.com/ge-semtk/semtk/wiki/Ingestion-Type-Handling#strings)

Note that string escape sequences such as \\n are further escaped in the triplestore.   Otherwise, for example, \\n and an actual line return would not be distinguishable.

**Comment by baoluomeng** [comment]
Verified. The problem was fixed.
