### ISSUE TITLE
rack nodegroups overwrite option

### ISSUE THREAD

**Issue by kityansiu** [ge-high-assurance/RACK#701]
See if this makes sense to add. When putting together an ingestion package, there may be some user specific ingestion nodegroups that get loaded with the data. Here's a snippet of an example LoadData.sh.

```
echo "Loading extra nodegroups for performance ..."
rack nodegroups import $BASEDIR/nodegroups
echo "Ingesting data..."
rack data import $BASEDIR/data/import.yaml
```

The next time LoadData.sh is run, it will fail because nodegroups already exist.
```
Storing nodegroups...                                       FAIL
[rack:74] ERROR: REST Endpoint Failure
http://localhost:12056/nodeGroupStore/storeItem: Rest service call did not succeed
Details:
b'"message":"operations failed."
"rationale":"nodeGroupStore/storeNodeGroup threw java.lang.Exception Unable to store item:  ID (acert-ingest-swcomponent1) already exists
```
It's hard to get the list of user specific ingestion nodegroups to delete them before running the load script again. The work around right now is to start from scratch with setup-rack.sh which deletes all the nodegroups (and all the data). 

@glguy @Ptival @kquick @cuddihyge, can you guys think of a better way? Thanks!

**Comment by cuddihyge** [comment]
I think we can re-jigger the cli and python layers to make it easy (maybe even default?) to overwrite nodegroups if they already exist, instead of the current behavior of throwing an error.
There is a gray area when two different performers create nodegroups with the same names, you wouldn't want to automatically smash over top of one with the other.  It would be better to flag an error.    But in real life most of the time we want to overwrite.  It is not technically difficult, we just need to manage these edge cases.

**Comment by glguy** [comment]
There was already code for this in python3-semtk. I've submitted a PR that fixes the issue https://github.com/ge-semtk/semtk-python3/pull/22

**Comment by kityansiu** [comment]
@glguy, is there a new CLI option for overwriting nodegroups now that the PR is merged in python3-semtk?

**Comment by glguy** [comment]
The default python3-semtk behavior is to overwrite on nodegroup directory import. Now that the fix is merged overwrite should be the observed rack behavior. However, this might only be in dev and not a released version of RACK. What version are you trying with?

**Comment by kityansiu** [comment]
Ah, I see! I verify that it works in dev.
