### ISSUE TITLE
Bring back the RACK cookbook

### ISSUE THREAD

**Issue by kityansiu** [ge-high-assurance/RACK#741]
Request from June 29 PI Meeting: bring back the cookbook. Can serve as sample queries that folks have asked for from data providers. 

Purpose: provide a common usage guide for the RACK data model so that data providers and data consumers can find common ground in how the model is used. 

Example recipes:

- Systems and Their Components -- this recipe recommends how hierarchical structure of systems can be represented
- Testing of System Implementations -- this recipe recommends how tests, test suites, and test results can be modeled and traced back to the requirement that it verifies, and the system component that the requirement governs.

See [RACK/wiki/RACK-Cookbook](https://github.com/ge-high-assurance/RACK/wiki/RACK-Cookbook) which was a start but needs to be updated.

**Comment by kityansiu** [comment]
Checked in some new files in the RACK.wiki repo. See branch cookbook.

**Comment by davearcher** [comment]
A few thoughts on the new draft cookbook:
- I removed the "under construction" logo and comments indicating that it's an early draft
- I'm thinking that the cardinalities in the pictures may not be accurate. Maybe remove them?
- In Recipe 1, I think that showing the Interfaces and System Development Activity in an expanded form might be good, to give a better picture of how the overall structure of data would look
- In Recipe 2, I start to get confused. I think we should show the way to model things, without the confusion of the red comments about how things are missing from or different from the blue diagrams. It's also at this point hard for the reader to understand what's meant by the green boxes and edges. May want to explain that these are abstractions of other diagrams that explain other parts of the model. Where we can, I think it would be good to articulate exactly which entity types are the "interfaces" between the current diagram and the green abstractions. This of course is a point where the generality we've left in the model will hurt, because it will be hard to explain what we're doing when that interface is a generic "entity" class...
- Recipe 3 has some of the same issues as Recipe 2: we should remove the red "differences", I think; and add specifics about the classes that are just "over the boundary" into the green abstractions
- In general, cardinalities aren't consistently shown. Maybe remove them, or always show them. One concern is that our choices for cardinalities aren't always defensible, so maybe removing them would be best
- I think Recipe 4 should be removed. Almost everything in the diagram has a red comment next to it; and I don't know that we have any evidence examples to show that this Recipe matches the real world.
- In Recipe 5, the red comment at bottom gives me an idea. While we don't have an entity class for "Requirements Specification" -- arguably too specific for our model -- we could specify an attribute of "Specification" to make it clear that the "kind" of specification expected in this recipe is a requirements specification. Or, we could sub-class Specification to be specific to Requirements specifications, which would make perhaps more sense because that way queries can be written based on model structure rather than interrogating string attributes. Either way, I think we need to resolve the red comment
- It seems like there are a bunch of other recipes we could specify, and that gives me another idea: perhaps we could specify recipes by illustrating with examples already in our Turnstile example data?
- I'm happy to develop more / fix current recipes.
- The pages referenced at right on the Cookbook may be out of date. Looks like some have not been updated since March?
-

**Comment by kityansiu** [comment]
Updated accordingly. Also added downloadable nodegroup files. Need to wait on finalized changes to TEST ontology before updating those recipes.
