### ISSUE TITLE
Add "manifest" to python/CLI

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#747]
Add manifest functionality to cli and python so ingestion packages and other similar capabilities can be executed without sh scripts and executed through the python GUI.

**Comment by glguy** [comment]
Yeah, I was thinking about how to do that this morning. My dream would be to make it generically support any flag, I just need to poke around the argparse library to see if that's feasible or if I just need to duplicate things.

**Comment by glguy** [comment]
I think we should probably resolve the paths all relative to where the manifest is currently located. I'll take a look today.

**Comment by glguy** [comment]
@weisenje fix is in 27bceb61cb515029b7ff8ee6ce837c4859ff9799

**Comment by glguy** [comment]
nested manifests seems fine.

On the topic of embedding clear statements in the manifests, it seems like one thing we'd want is a way to clear out data from the web UI when ingesting a new package. It feels slightly off for the ingestion package to do all the clearing out. Maybe we need both?

**Comment by glguy** [comment]
I want to add something to support clear, but I don't believe that emulating the shell script is the right level of abstraction, my current plan to implement is a way for a manifest to declare what it is that it imports so that if you run it in a clear-first mode it knows what to wipe out. It feels like a miss to merely treat these manifests as a limited shell scripting environment. I should have a version of the above today or early to morrow.

**Comment by cuddihyge** [comment]
Basic functionality is implemented and pushed to main.   Moving this to "ready for review" and we'll add improvements as new issues.
