### ISSUE TITLE
Bump Fuseki to latest version (4.9.0)

### ISSUE THREAD

**Issue by Ptival** [ge-high-assurance/RACK#773]
Should the doc be updated?

**Comment by tuxji** [comment]
Yes, the rack-box doc is out of date.  We resolved the issues preventing us from bumping Fuseki's version since originally starting with Fuseki 3.16.0.  In fact, I just realized that Fuseki 4.5.0 is no longer the latest version and we should bump it to Fuseki 4.6.1.  

I've updated rack-box/README.md to stop mentioning 3.16.0. When shall we bump Fuseki again (now or later)?

**Comment by tuxji** [comment]
Update: As of today, RACK uses Fuseki 4.7.0 but the latest is 4.9.0, so we should bump Fuseki to the latest again.

**Comment by tuxji** [comment]
Done in PR #982
