### ISSUE TITLE
Add entity-resolution to the ingestion process (cli / manifest)

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#801]
Perhaps the end of a manifest has a list of entity resolution processes to kick off.
Each has the input graph(s) and output graph

**Comment by cuddihyge** [comment]
combine_entities_in_conn() is the python function

**Comment by cuddihyge** [comment]
Where do I get the ontology for entity resolution? @cuddihyge 

Without it loaded I get an error when trying to test run loading a manifest with resolution (unsurprisingly)

[rack:74] ERROR: REST Endpoint Failure
http://localhost:12058/nodeGroupExecution/dispatchCombineEntitiesInConn: Rest service call did not succeed
Details:
b'"message":"operations failed."
"rationale":"Can\'t find class in model: http://research.ge.com/semtk/EntityResolution#SameAs"
"status":"failure"'

**Comment by cuddihyge** [comment]
This is a bug on my end.  I'll re-open #800 and push a fix today. @glguy

**Comment by cuddihyge** [comment]
@glguy Changed my mind.  Not sure if it's a bug on my end.  Not positive what the best error handling should be.
Asking to perform entity resolution when there is no class even in the model seems like it should indeed throw an error.
However this means our manifest/UI pipeline would have to be more sophisticated.   It would have to know whether entity resolution should be attempted.

The alternative would considering entity resolution with no SameAs class in the model as a silent success.   Seems like that could come back to bite us.   Ideas?   @weisenje  @glguy   ?

For testing, you can start by loading owl from SemTK [EntityResolution.owl](https://github.com/ge-semtk/semtk/blob/master/sparqlGraphLibrary/src/main/resources/semantics/OwlModels/EntityResolution.owl)

**Comment by cuddihyge** [comment]
@glguy after some thought and chat with @weisenje it seems that one good path forward would be to put an entity resolution command into the manifest.   If that command is present and there is no EntityResolution#SameAs class loaded, then the error will make sense.

Just to stay ahead of things, the manifest might have some options:

1. copy to default graph, perform entity resolution, optimize
2. copy to default graph, optimize
3. none of the above
  
@glguy would have the best insight into whether these should be single atomic options, or specified separately but still always done in the correct order at the end of a load.

So this wouldn't affect the RACK-UI, correct?

**Comment by glguy** [comment]
I've started a PR #847 for a flag that consolidates the triple store into the default graph and runs entity resolution at the end of an import. I probably need to split off running entity resolution as a separate flag, however, if there are case where we won't have actually loaded the entity resolution ontology.

I think it should be an error to request entity resolution when you aren't using it.

I think that the manifest should describe the dataset and that the manifest should be constructed in a way so as to be useful for importing into other manifests. Global actions like "clear the triple store" or "merge everything into the default graph" aren't compositional. These feel like aspects of a particular ingestion rather than aspects of a dataset. It seems like a principle that we should maintain that manifests are always suitable to be imported into a future manifest in order to support an additive model of incremental assurance. I don't want people to have to edit past data to add new data, and the manifest files for a particular dataset feel like they should be thought of as part of the dataset.
