### ISSUE TITLE
RACK-UI: add /optimize endpoint

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#823]
Add an endpoint to the RACK-UI that will run the Fuseki optimization script.
- [x] demonstrate that it's possible to add an endpoint to a Dash app **(Jenny)**
- [x] determine if runs long enough to need asynchronous call (synchronous is fine, biggest dataset finishes in <5 sec) **(Jenny)**
- [x] coordinate with Eric what the endpoint should return **(Jenny)**
- [x] make the endpoint run cli/optimize.sh **(Val)
- [x] test in Docker and VM (not supported on Windows local deployment)

**Comment by glguy** [comment]
That seems fine to me; I don't know what other outputs we'd know to report.

**Comment by Ptival** [comment]
As @glguy mentioned by email, I believe some possible options are:

- Giving more rights to `rackui`, which sounds a bit like giving up entirely on separation,

- Making `root` own `optimize.sh` and giving it a `setuid`. In a private virtual machine, this is pretty innocuous. In a shared setting, this could enable denial-of-service if people are able to run the script repeatedly.

- Otherwise, we would need to come up with some intermediate solution, where the UI is able to request that the script is run, and some process with the appropriate permissions is able to perform that request on its behalf.

@tuxji Do you have any ideas in this space? Are we already doing something similar?

**Comment by tuxji** [comment]
I have the following thoughts:
- When you replace a fuseki file, you want the file to remain owned by the fuseki user
- Therefore, you want to run cli/optimize.sh as fuseki, not as root
- The rack-ui app currently runs as the rackui user but could run as fuseki instead
- Systemd allows you to run executables or shell scripts as any user you wish
- However, you still need to be root to run explicit systemctl start/stop commands
- Systemd can run a script after a service is restarted or trigger systemd services based on conditions

I think your best approach would be to find a way to make systemd run your script when you want it to, or even easier (if it works), run all your commands as the fuseki user including stopping and starting the fuseki server with the fuseki distribution's own [script](https://github.com/apache/jena/blob/main/jena-fuseki2/apache-jena-fuseki/fuseki).  That is, try the following first:

- edit cli/optimize.sh
- replace "systemctl stop fuseki" with "/opt/fuseki/fuseki stop"
- replace "systemctl start fuseki" with "/opt/fuseki/fuseki start"
- edit rack-ui/rackui.service
- replace User=rackui with User=fuseki

Rebuild the docker image, hit the optimize endpoint, cross your fingers, and hope that cli/optimize.sh stops and starts the fuseki server successfully even though the server was originally started by systemd (/etc/systemd/system/fuseki.service) rather than by /opt/fuseki/fuseki.  Maybe they play nice together, maybe they don't play together, but you can find out.

**Comment by Ptival** [comment]
I started looking into this, it's a little more nuanced.

Currently, the `/opt/jena/`/`/opt/fuseki/` directories and the executables they contain are owned by `root`, while the contents of `/etc/fuseki` are owned by `fuseki`.

So, as `fuseki`, I have not been able to run `/opt/fuseki/fuseki {start,stop}`, permission denied. But I think I was able to run the `systemctl {start,stop}` variants.

Likewise, to run the optimization, we run `/opt/jena/bin/tdbstats`, owned by `root`, so the resulting `/etc/fuseki/databases/RACK/stats.opt` is owned by `root`. It is, however, chmod 644, and given fuseki only needs to read it, this does not prevent restarting fuseki.

Also, @weisenje , I'm wondering how you were running `cli/optimize.sh` as `fuseki`, since it's in user `ubuntu`'s home directory, and it shouldn't be readable by anyone but them? Had you already started changing permissions?

**Comment by Ptival** [comment]
Oh, one difference is that I switched the base image from `ubuntu:20.04` to `ubuntu:22.04`, because I keep getting those `Pillow` errors on the 20.04 version.

This might be why I get a discrepancy on the permissions of `ubuntu`'s home directory.

**Comment by Ptival** [comment]
Alright, so once all the permissions problems have been resolved, it turns out that `/opt/fuseki/fuseki stop` is not enough, because the fuseki service immediately restarts the process that owns the lock to the database. It works with `systemctl stop fuseki`.

Additionally, if we change the owner of `/etc/fuseki/fuseki` to be `fuseki`, then we get a permission error when restarting fuseki, because it tries to write to `/var/log/journal/fuseki.service.log`, owned by `root`.

**Comment by Ptival** [comment]
I think this may be the path of least resistance:

- Install `sudo` in the VM,
- Add `rackui` to the sudoers,
- User `rackui` runs `sudo cli/optimize.sh`, which runs as `root`, and does `chown fuseki /path/to/stats.opt` before restarting Fuseki.

**Comment by Ptival** [comment]
Struggling to build the Virtualbox version, for the same reason I have never been able to build Docker images on 20.04: the Pillow package seems incompatible with older versions of Python.

I'm confused as to why the CI does not run into the same problems as I do.

To build Docker images, I've had to replace `ubuntu-20.04` to `ubuntu-22.04`.

It seems like, to build the Virtualbox images, I'm going to have to replace `focal64` with `jammy64`.

Anyway, @tuxji just told me how I could ask the CI to try to build my branch for me, so I'll give this a try!

**Comment by tuxji** [comment]
@Ptival I suspect the reason why you're struggling with incompatible versions of the Pillow package is that either your codebase or your rack-box/files are not exactly the same versions that the CI uses.  Currently `cli/requirements.txt` specifies Pillow==9.0.1 at line 13 and `.github/workflows/assemble-files.yml` packages rack-cli.tar.gz with Pillow 9.0.1 as one of the wheels accordingly.  If you have bumped the Pillow version in your `cli/requirements.txt` or packaged your `rack-box/files/rack-cli.tar.gz` with Pillow > 9.0.1, then you do need to bump Ubuntu from 20.04 to 22.04 as well.

Pillow 9.0.1 has a CVE filed against it, so we probably should bump Pillow from 9.0.1 to 9.0.3 anyway even though we'd also have to bump all our Ubuntu workflows, Docker images, and VMs from 20.04 to 22.04 as well.  I'm just waiting for that task to become a priority to work on, especially since it will affect many team members' development environments (anyone using Ubuntu 20.04 as their dev env will have to transition to 22.04 to keep up).  Please ask Kit to pick a good time for the team to upgrade their environments.

**Comment by glguy** [comment]
Something's special about the first fuseki launched. Systemctl restart fuseki isn't cutting it. If I kill off that first fuseki the remaining ones seem better behaved. I'm poking around to see what's happening here.

**Comment by glguy** [comment]
> 

Yes, the reason we get the error with the restart button is that fuseki doesn't stop; it just starts a new one and then new one can't bind the port because the old one is still using it.
