### ISSUE TITLE
Have RACK-UI/CLI call the SemTK manifest loader

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#911]
Remove the code from python and call SemTK's manifest loader instead.

Notes
will need to "grep" for "warning:" lines to decide the log level  & match current functionality
can't rip out the code for downloading nodegroups (yet)

- [x] CLI: call semtk-python3 client directly, optimize if needed
- [x] CLI: remove support for manifest.yaml and running individual ingestions steps -- only accept zip file
- [x] RACK UI: call semtk-python3 client directly, optimize if needed _(works, pushed to dev-test)_
- [x] RACK UI: remove Turnstile button _(added separate issues to create Turnstile zip as release asset and link from RACK UI)_
- [x] consolidate some variables/logic that appear in both RACK UI and CLI

**Comment by glguy** [comment]
Is the API endpoint for this available now? Can you point me to it if so?

**Comment by glguy** [comment]
When I run this method I get some output about not being implemented. I just rebuilt my docker image, but did I get the wrong target?

```
$ rack manifest import turnstile.zip
Loading ingestion package...
Loaded ontologies (not implemented yet)
Loaded nodegroups (not implemented yet)
Loaded instance data (not implemented yet)
Load complete
```

Second, is there any computer-readable way to know if ingestion succeeded so that I can set the return code or color something bright red, or something like that? When I tried sending an empty file, for example, I got `Error: No zipped contents` but I don't see a way for the tool to know that this was an error condition generically.

**Comment by glguy** [comment]
See #929

**Comment by glguy** [comment]
Can the RACK UI just pass the zip file through to the python code, or just call the Java API directly? I was thinking that the behavior when called on just a manifest.yaml was kind of the development mode and the ingestion was simulated in place. The change I was considering was removing support for that path altogether and requiring users to `manifest build` first before trying to import the package.
