### ISSUE TITLE
Disallow manifest loading outside of footprint

### ISSUE THREAD

**Issue by weisenje** [ge-high-assurance/RACK#921]
The load ingestion package routines (both CLI and ported SemTK) do not currently check that a load aligns with its stated footprint.

This means that 1) the clear/copy-to-graph (dictated by footprint) may not clear/copy the right data 2) users can load to graphs they're not intending to

@glguy @cuddihyge should we consider adding a check for this?

**Comment by glguy** [comment]
If we're going to do this check it probably needs to work such that:

* model and data imports can only use graphs mentioned by their immediate manifest's footprint
* nested manifests footprints are checked to be a subset of the parent manifests
* It's probably OK for a graph to be mentioned in the footprint and not actually used in a data or model import (I could imagine this happening because someone wanted to use a bigger set of graphs in the generated connection strings for some other data generation mechanism or because someone commented out a import while testing something)

If we're going to add this I'm thinking that I won't add it to the CLI as it's a "nice to have" and the CLI implementation will be going away soon.

**Comment by glguy** [comment]
This is actually a rather interesting case.

I *think* these entries should be in the model. We're loading them with CSV files as a convenience.

We might want to just unify data and model ingestion into one thing. I'm out today but I'd like to think about what merging these things would mean on Monday.

If we don't want to change anything, we should migrate these files to SADL and ingest them from OWL.

**Comment by glguy** [comment]
I think we should unify the model and data ingestion files into a single format. We can specify which thing is to be loaded as an extra parameter to the current data.yaml format. It's an accident of the way the SemTK API was that these things we created to be different. Only the `upload_owl` API endpoint had a `model_or_data` parameter, but this seems to be something to fix rather than to enshrine in the ingestion process.

Let's discuss this today!

**Comment by glguy** [comment]
So now we have checks for data imports, model imports, and submanifests?
